### ISSUE TITLE
Add integration testing

### ISSUE THREAD

**Issue by fredericmarx** [fredericmarx/weh-matter#1]
So far there is only a test for the transform module.

It would probably make sense to at least test if weh runs the plugin without errors, but I'm not 100% sure how to best do that.

**Comment by ghost** [comment]
i've been thinking about this as well - what we could do is implement a sort of `dry-run`-ish option in core, which would still perform the transforms, but not actually write anything to disk. as for reading, maybe there could be a way to somehow make weh accept a manually constructed `files` object? perhaps you could even build some test helpers around that and publish it as a module
